name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: 'íº€ Features'
    labels:
      - 'feature'
  - title: 'í°› Bug Fixes'
    labels:
      - 'bug'
  - title: 'í»  Maintenance'
    labels:
      - 'chore'
      - 'refactor'

version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'security'
      - 'chore'
      
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

template: |
  ## Changes
  $CHANGES

