name: Release Drafter

on:
  push:
    branches:
      - main
      - '5.0.x'
      - '5.1.x'
      - '6.0.x'
  pull_request:
    branches:
      - main
      - '5.0.x'
      - '5.1.x'
      - '6.0.x'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Draft Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
